#!/usr/bin/env bash

unset assignment_name
max_points=0

print_usage() {
cat <<EOM
Usage: $(basename "${0}") [-p max-points] assignment-name

Option descriptions:
    * -p max-points    Point maximum for the assignment, e.g., 100. By default
                       this is 0 (meaning the total points deducted is displayed
                       instead).
EOM
}

while getopts "p:" flag; do
    case ${flag} in
        p) max_points="${OPTARG}" ;;
    esac
done

shift $(($OPTIND - 1))

assignment_name="${1}"

if [[ -z "${assignment_name}" ]]; then
    print_usage
    exit 1
fi

for assignment in ./working-dir/"${assignment_name}"*/grade-info.md; do
    total=$(\
        sed -n 's|^\* .*\[-\([0-9\.]*\)\]|\1|p' "${assignment}" \
        | awk '{ total += $1 } END { print ('"${max_points}"' - total) }');
    student=$(\
        sed "s|.*${assignment_name}-\(.*\)/grade-info.md|\1|g" \
            <<< ${assignment})
    echo "${student} ${total}"
done | sort -f

